version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_tasks
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_tasks
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

volumes:
  db_data:
