version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_tasks
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_tasks
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: tasks_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "
        composer install &&
        composer require --dev zircote/swagger-php:^4.0 symfony/console doctrine/annotations &&
        vendor/bin/openapi app --output swagger.json &&
        apache2-foreground
      "

volumes:
  db_data:
